// Google OAuth2 Configuration
// Credentials are loaded from environment variables for security

export const GOOGLE_CONFIG = {
  clientId: process.env.GOOGLE_CLIENT_ID || '',
  clientSecret: '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',
  spreadsheetId: process.env.GOOGLE_SPREADSHEET_ID || '',
  redirectUri: 'http://localhost:3334/api/auth/callback',
  scopes: [
    'https://www.googleapis.com/auth/spreadsheets',
    'https://www.googleapis.com/auth/drive.readonly',
    'https://www.googleapis.com/auth/calendar',
  ],
};

// All 72 columns from the Prontuário form (exact order from Google Forms)
export const PRONTUARIO_COLUMNS = [
  'Carimbo de data/hora',
  'Nome completo:',
  'Número da carterinha:',
  'Qual o plano de saúde?',
  'E-mail:',
  'Telefone: ',
  'Data de nascimento:',
  'Sexo:',
  'Rg. nº:',
  'CPF:',
  'Naturalidade:',
  'Endereço Atual:',
  'Complemento do endereço:',
  'CEP:',
  'Profissão:',
  'Contato de emergência:  ',
  'Indicado por:',
  'Caso seja outro Dentista ou profissional da saúde escreva abaixo:',
  'No momento presente, você se encontra gripado/resfriado/sinusite?',
  'Queixa principal:',
  'Alguma alergia? Se sim, qual(is)?',
  'Sua pressão é:',
  'Tem ou teve algum problema no coração?',
  'Tem diabetes?',
  'Quando se corta há um sangramento:',
  'Sua cicatrização é:',
  'Já fez alguma cirurgia? Se sim, qual(is)?',
  'Gestante?',
  'Está ou esteve recentemente em tratamento médico? Se sim, qual(is)?',
  'Está tomando alguma medicação. Se sim, qual(is)?',
  'Febre reumática:',
  'Hepatite:',
  'Hipertensão Arterial:',
  'Portador do vírus HIV:',
  'Bebida alcoólica:',
  'Problema renal:',
  'Problema respiratório:',
  'Problema gástrico:',
  'Problema articular/reumático:',
  'Anemia:',
  'Internação recente:',
  'Alteração na coagulação sanguínea:',
  'Você tem medo de dentista?',
  'Já apresentou reação com anestesia bucal?',
  'Apresenta dor nos dentes ou na gengiva?',
  'Nota sangramento na gengiva?',
  'Escova os dentes quantas vezes por dia? ',
  'Usa fio dental?',
  'Sente dores ou estalos no maxilar ou no ouvido?',
  'Ranges os dentes de dia ou a noite?',
  'Já teve alguma ferida ou bolha nos lábios ou na gengiva?',
  'Consome alimentados pigmentados em alta frequência? ',
  'Fumante:',
  'Nacionalidade:',
  'Visto permanente?',
  'Validade:',
  'Número do passaporte:',
  'País do passaporte:',
  'Quando foi o seu último tratamento dentário?',
  'Qual foi o seu último tratamento dentário?',
  'Qual será o tipo de Procedimento que você irá fazer?',
  'O que te motivou a buscar tratamento estético com harmonização orofacial?',
  'O que você gostaria de melhorar em sua face?',
  'Possui alguma referência estética específica ou algum resultado desejado?',
  'Já teve alguma reação adversa a ANESTÉSICO LOCAL?',
  'Tem histórico de herpes labial ou outras infecções virais?',
  'Já realizou algum procedimento de harmonização orofacial antes?',
  'Possui alguma restrição ou fobia relacionada a agulhas ou procedimento invasivos?',
  'Já teve alguma reação adversa a TOXINA BOTULÍNICA?',
  'Já teve alguma reação adversa a PREENCHEDOR FACIAL?',
  'Coluna 69',
  'Atualizado? Favor Atualizar quando paciente retornar ',
];

// Friendly labels for the columns (used in UI)
export const COLUMN_LABELS: Record<string, string> = {
  'Carimbo de data/hora': 'Data de Cadastro',
  'Nome completo:': 'Nome Completo',
  'Número da carterinha:': 'Nº Carteirinha',
  'Qual o plano de saúde?': 'Plano de Saúde',
  'E-mail:': 'E-mail',
  'Telefone: ': 'Telefone',
  'Data de nascimento:': 'Data de Nascimento',
  'Sexo:': 'Sexo',
  'Rg. nº:': 'RG',
  'CPF:': 'CPF',
  'Naturalidade:': 'Naturalidade',
  'Endereço Atual:': 'Endereço',
  'Complemento do endereço:': 'Complemento',
  'CEP:': 'CEP',
  'Profissão:': 'Profissão',
  'Contato de emergência:  ': 'Contato de Emergência',
  'Indicado por:': 'Indicado por',
  'Queixa principal:': 'Queixa Principal',
  'Alguma alergia? Se sim, qual(is)?': 'Alergias',
  'Sua pressão é:': 'Pressão Arterial',
  'Tem ou teve algum problema no coração?': 'Problema Cardíaco',
  'Tem diabetes?': 'Diabetes',
  'Fumante:': 'Fumante',
  'Atualizado? Favor Atualizar quando paciente retornar ': 'Status de Atualização',
};

// Column groups for organized display
export const COLUMN_GROUPS = [
  {
    title: '📋 Dados Pessoais',
    columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
  },
  {
    title: '🏥 Anamnese Médica',
    columns: [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
  },
  {
    title: '🩺 Condições de Saúde',
    columns: [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41],
  },
  {
    title: '🦷 Saúde Bucal',
    columns: [42, 43, 44, 45, 46, 47, 48, 49, 50, 51],
  },
  {
    title: '🌍 Nacionalidade e Documentos',
    columns: [52, 53, 54, 55, 56, 57],
  },
  {
    title: '📝 Tratamento e Procedimento',
    columns: [58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
  },
  {
    title: '⚙️ Controle',
    columns: [70, 71],
  },
];
